### ISSUE TITLE
i used this code both in my local and google colab

### ISSUE THREAD

**Issue by Varun-Mayilvaganan** [lindsey98/PhishIntention#29]
Config '/content/PhishIntention/configs/faster_rcnn_web.yaml' has no VERSION. Assuming it to be compatible with latest v2.
Traceback (most recent call last):
  File "/content/PhishIntention/phishintention.py", line 174, in <module>
    phishintention_cls = PhishIntentionWrapper()
  File "/content/PhishIntention/phishintention.py", line 24, in __init__
    self._load_config()
  File "/content/PhishIntention/phishintention.py", line 28, in _load_config
    self.SIAMESE_THRE, self.LOGO_FEATS, self.LOGO_FILES, self.DOMAIN_MAP_PATH = load_config()
  File "/content/PhishIntention/configs.py", line 27, in load_config
    AWL_MODEL = config_rcnn(cfg_path=configs['AWL_MODEL']['CFG_PATH'],
  File "/content/PhishIntention/modules/awl_detector.py", line 35, in config_rcnn
    predictor = DefaultPredictor(cfg)
  File "/usr/local/lib/python3.10/dist-packages/detectron2/engine/defaults.py", line 288, in __init__
    checkpointer.load(cfg.MODEL.WEIGHTS)
  File "/usr/local/lib/python3.10/dist-packages/detectron2/checkpoint/detection_checkpoint.py", line 62, in load
    ret = super().load(path, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/fvcore/common/checkpoint.py", line 153, in load
    assert os.path.isfile(path), "Checkpoint {} not found!".format(path)
AssertionError: Checkpoint /content/PhishIntention/models/layout_detector.pth not found! 
getting an error in this while running =>  !python phishintention.py --folder datasets/test_sites --output_txt test.txt
![Screenshot (220)](https://github.com/user-attachments/assets/69d4e495-8691-42ba-ab2d-63a02478a093)

**Comment by lindsey98** [comment]
please refer to https://github.com/lindsey98/PhishIntention/blob/main/setup.sh#L73 to Line 121 to download all the pre-trained models

**Comment by Varun-Mayilvaganan** [comment]
Hi lindsey,
I solved the above error but even for malicious websites it shows me benign ; why is that?

![Screenshot (17)](https://github.com/user-attachments/assets/68b0a589-6bff-4a84-9028-7c77e2c7455f)

Thanks in advance!

**Comment by lindsey98** [comment]
Hi, I suspect the reference list is not properly loaded, please check whether models/expand_targetlist has been unzipped and there are 277 folders inside.

**Comment by Varun-Mayilvaganan** [comment]
Hi,
I tried it but the same issue arising!
![Screenshot (18)](https://github.com/user-attachments/assets/496ec2bc-85df-4c3f-b03b-8815a86d91b0)

**Comment by lindsey98** [comment]
1. make sure the directory looks like this:
```
|_ models/
   |__ expand_targetlist/
      |____ Amazon/
      |____....
```

2. Go to https://github.com/lindsey98/PhishIntention/blob/main/phishintention.py#L28
and set load_config(reload_targetlist=True)

**Comment by Varun-Mayilvaganan** [comment]
We need to change in the line you mentioned or at configs.py - L14?

**Comment by lindsey98** [comment]
change this line only

**Comment by Varun-Mayilvaganan** [comment]
![Screenshot (21)](https://github.com/user-attachments/assets/24287412-24ee-4703-998e-9f31d6386fb7)
loaded all reference files and then this error pops up

**Comment by lindsey98** [comment]
Not very sure about this error, you can try the following:

Step 1: Download the chromedriver executable file manually https://sites.google.com/chromium.org/driver/downloads. Make sure it matches your chrome version
Step 2: Point the webdriver to this chromedriver path, replace this line https://github.com/lindsey98/PhishIntention/blob/main/utils/web_utils.py#L153 with
driver = webdriver.Chrome(chrome_options=options, executable_path='path to the chromedriver executable')

**Comment by Varun-Mayilvaganan** [comment]
i am using WSL so there will be any path compatibility issues in paths?

**Comment by Varun-Mayilvaganan** [comment]
Thanks for your time!
The project is working fine with no issues but i need to ask for the new testing sites, why it is predicting benign?

**Comment by lindsey98** [comment]
It's likely because the [accounts.g.cdcde.com] is dead so the CRP intention cannot be confirmed. You can try on some fresh phishing feeds https://openphish.com/

**Comment by Varun-Mayilvaganan** [comment]
Hi lindsey, 
I worked on phishintention but the result is not that much accurate due to new evolving phishing websites. so give me an idea how i can improve it.
note : i gave new websites not in target list

**Comment by lindsey98** [comment]
Hi Varun, one way is to expand the target list to support new brands. For example, if you would like to support a new brand called DBS:

- Step 1: Look for some DBS logo variants from Google Images or [Logopedia](https://logos.fandom.com/wiki/Logopedia), etc.
- Step 2: Create a new folder ``models/expand_targetlist/dbs/`` and move all the .png files inside.
- Step 3: Modify this file ``models/domain_map.pkl`` , it is a dictionary that maps brand to domain(s). Suppose DBS's official domain is dbs.com.
```
import pickle 
with open('./models/domain_map.pkl', 'rb') as handle:     
    domain_map = pickle.load(handle)
if 'dbs' not in domain_map.keys():     
    domain_map['dbs'] = ['dbs.com']  
with open('./models/domain_map.pkl', 'wb') as handle:     
    pickle.dump(domain_map, handle)
```
- Step 4: Remove LOGO_FILES.npy and LOGO_FEATS.npy, and run again
